force-app/main/default/objects/Record_Type_Mapping__mdt/Record_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Record Type Mapping</label>
    <pluralLabel>Record Type Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Record_Type_Mapping__mdt/fields/Search_Key__c.field-meta.xml
<CustomField>
    <fullName>Search_Key__c</fullName>
    <label>Search Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/recordTypeMappings.cls
public class recordTypeMappings {
	
     private static Map<String, Record_Type_Mapping__mdt> globalDescribe ;
    
     public  recordTypeMappings()
       {
         if(globalDescribe == null)  globalDescribe = fetchValues();     
       }
    
    private Map<String,Record_Type_Mapping__mdt> fetchValues()
    {
        Map<String,Record_Type_Mapping__mdt> outputMap = new  Map<String,Record_Type_Mapping__mdt>();        
        for(Record_Type_Mapping__mdt c  : Record_Type_Mapping__mdt.getall().values())
        {
            if(!outputMap.containsKey(c.Search_Key__c))
            {
              outputMap.put(c.Search_Key__c,c);
            }
        }
        return outputMap;
    }
    
    public  String getRecordTypeName(String searchKey)
    {
        if(globalDescribe.get(searchKey) != null)
        {
            return globalDescribe.get(searchKey).Record_Type_Name__c;
        }
        else return null; // we will actually performs the logic to directly query the custom metadata record 
    }
}